
[recca0120-vscode-phpunit]
src.openvsx = "recca0120.vscode-phpunit"
fetch.openvsx = "recca0120.vscode-phpunit"

[recca0120-vscode-phpunit.passthru]
name = "vscode-phpunit"
publisher = "recca0120"
marketplaceName = "vscode-phpunit"
marketplacePublisher = "recca0120"
license = "mit"
changelog = "https://open-vsx.org/api/recca0120/vscode-phpunit/3.0.16/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/recca0120/vscode-phpunit/3.0.16/file/recca0120.vscode-phpunit-3.0.16.vsix"
homepage = "https://github.com/recca0120/vscode-phpunit#readme"

[j-f1-yoink-for-vscode]
src.openvsx = "j-f1.yoink-for-vscode"
fetch.openvsx = "j-f1.yoink-for-vscode"

[j-f1-yoink-for-vscode.passthru]
name = "yoink-for-vscode"
publisher = "j-f1"
marketplaceName = "yoink-for-vscode"
marketplacePublisher = "j-f1"
license = "mit"
changelog = "https://open-vsx.org/api/j-f1/yoink-for-vscode/1.0.0/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/j-f1/yoink-for-vscode/1.0.0/file/j-f1.yoink-for-vscode-1.0.0.vsix"
homepage = "https://github.com/j-f1/yoink-vscode#readme"

[kieler-pasta]
src.openvsx = "kieler.pasta"
fetch.openvsx = "kieler.pasta"

[kieler-pasta.passthru]
name = "pasta"
publisher = "kieler"
marketplaceName = "pasta"
marketplacePublisher = "kieler"
license = "epl20"
downloadPage = "https://open-vsx.org/api/kieler/pasta/0.1.1/file/kieler.pasta-0.1.1.vsix"
homepage = "https://github.com/kieler/stpa#readme"

[j-f1-vscode-smart-transpose]
src.openvsx = "j-f1.vscode-smart-transpose"
fetch.openvsx = "j-f1.vscode-smart-transpose"

[j-f1-vscode-smart-transpose.passthru]
name = "vscode-smart-transpose"
publisher = "j-f1"
marketplaceName = "vscode-smart-transpose"
marketplacePublisher = "j-f1"
license = "mit"
downloadPage = "https://open-vsx.org/api/j-f1/vscode-smart-transpose/1.0.0/file/j-f1.vscode-smart-transpose-1.0.0.vsix"
homepage = "https://github.com/j-f1/vscode-smart-transpose#readme"

[arm-keil-studio-pack-web]
src.openvsx = "arm.keil-studio-pack-web"
fetch.openvsx = "arm.keil-studio-pack-web"

[arm-keil-studio-pack-web.passthru]
name = "keil-studio-pack-web"
publisher = "arm"
marketplaceName = "keil-studio-pack-web"
marketplacePublisher = "arm"
license = "mit"
downloadPage = "https://open-vsx.org/api/arm/keil-studio-pack-web/web/1.2.2/file/Arm.keil-studio-pack-web-1.2.2@web.vsix"
homepage = "https://github.com/ARM-software/vscode-keil-studio-pack#readme"

[kahole-magit]
src.openvsx = "kahole.magit"
fetch.openvsx = "kahole.magit"

[kahole-magit.passthru]
name = "magit"
publisher = "kahole"
marketplaceName = "magit"
marketplacePublisher = "kahole"
license = "mit"
changelog = "https://open-vsx.org/api/kahole/magit/0.6.36/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/kahole/magit/0.6.36/file/kahole.magit-0.6.36.vsix"
homepage = "https://github.com/kahole/edamagit/blob/master/README.md"

[j-f1-sf-symbols]
src.openvsx = "j-f1.sf-symbols"
fetch.openvsx = "j-f1.sf-symbols"

[j-f1-sf-symbols.passthru]
name = "sf-symbols"
publisher = "j-f1"
marketplaceName = "sf-symbols"
marketplacePublisher = "j-f1"
license = "mit"
downloadPage = "https://open-vsx.org/api/j-f1/sf-symbols/1.1.0/file/j-f1.sf-symbols-1.1.0.vsix"
homepage = "https://github.com/j-f1/sf-symbols-vscode#readme"

[bmd-stm32-for-vscode]
src.openvsx = "bmd.stm32-for-vscode"
fetch.openvsx = "bmd.stm32-for-vscode"

[bmd-stm32-for-vscode.passthru]
name = "stm32-for-vscode"
publisher = "bmd"
marketplaceName = "stm32-for-vscode"
marketplacePublisher = "bmd"
license = "mit"
changelog = "https://open-vsx.org/api/bmd/stm32-for-vscode/3.2.3/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/bmd/stm32-for-vscode/3.2.3/file/bmd.stm32-for-vscode-3.2.3.vsix"
homepage = "https://github.com/bmd-studio/stm32-for-vscode#readme"

[FelixAngelov-mason]
src.openvsx = "FelixAngelov.mason"
fetch.openvsx = "FelixAngelov.mason"

[FelixAngelov-mason.passthru]
name = "mason"
publisher = "felixangelov"
marketplaceName = "mason"
marketplacePublisher = "FelixAngelov"
license = "mit"
changelog = "https://open-vsx.org/api/FelixAngelov/mason/0.1.7/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/FelixAngelov/mason/0.1.7/file/FelixAngelov.mason-0.1.7.vsix"
homepage = "https://brickhub.dev"

[seatonjiang-gitmoji-vscode]
src.openvsx = "seatonjiang.gitmoji-vscode"
fetch.openvsx = "seatonjiang.gitmoji-vscode"

[seatonjiang-gitmoji-vscode.passthru]
name = "gitmoji-vscode"
publisher = "seatonjiang"
marketplaceName = "gitmoji-vscode"
marketplacePublisher = "seatonjiang"
license = "mit"
changelog = "https://open-vsx.org/api/seatonjiang/gitmoji-vscode/1.2.2/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/seatonjiang/gitmoji-vscode/1.2.2/file/seatonjiang.gitmoji-vscode-1.2.2.vsix"
homepage = "https://github.com/seatonjiang/gitmoji-vscode/blob/main/README.md"


[codechecker-codechecker]
src.openvsx = "codechecker.codechecker"
fetch.openvsx = "codechecker.codechecker"

[codechecker-codechecker.passthru]
name = "codechecker"
publisher = "codechecker"
marketplaceName = "codechecker"
marketplacePublisher = "codechecker"
license = "asl20"
downloadPage = "https://open-vsx.org/api/codechecker/codechecker/1.4.0/file/codechecker.codechecker-1.4.0.vsix"
homepage = "https://github.com/Ericsson/CodeCheckerVSCodePlugin/tree/main/README.md"

[cloudstudio-gitcommits]
src.openvsx = "cloudstudio.gitcommits"
fetch.openvsx = "cloudstudio.gitcommits"

[cloudstudio-gitcommits.passthru]
name = "gitcommits"
publisher = "cloudstudio"
marketplaceName = "gitcommits"
marketplacePublisher = "cloudstudio"
license = "mit"
downloadPage = "https://open-vsx.org/api/cloudstudio/gitcommits/0.0.3/file/CloudStudio.gitcommits-0.0.3.vsix"
homepage = ""

[melmass-vscode-mono-workspace]
src.openvsx = "melmass.vscode-mono-workspace"
fetch.openvsx = "melmass.vscode-mono-workspace"

[melmass-vscode-mono-workspace.passthru]
name = "vscode-mono-workspace"
publisher = "melmass"
marketplaceName = "vscode-mono-workspace"
marketplacePublisher = "melmass"
license = "mit"
changelog = "https://open-vsx.org/api/melmass/vscode-mono-workspace/win32-x64/1.4.1/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/melmass/vscode-mono-workspace/win32-x64/1.4.1/file/melMass.vscode-mono-workspace-1.4.1@win32-x64.vsix"
homepage = "https://github.com/mtb-tools/vscode-mono-workspace#readme"

[appliedengdesign-vscode-gcode-syntax]
src.openvsx = "appliedengdesign.vscode-gcode-syntax"
fetch.openvsx = "appliedengdesign.vscode-gcode-syntax"

[appliedengdesign-vscode-gcode-syntax.passthru]
name = "vscode-gcode-syntax"
publisher = "appliedengdesign"
marketplaceName = "vscode-gcode-syntax"
marketplacePublisher = "appliedengdesign"
license = "mit"
downloadPage = "https://open-vsx.org/api/appliedengdesign/vscode-gcode-syntax/0.7.7/file/appliedengdesign.vscode-gcode-syntax-0.7.7.vsix"
homepage = "https://github.com/appliedengdesign/vscode-gcode-syntax"

[openCAESAR-oml-luxor]
src.openvsx = "openCAESAR.oml-luxor"
fetch.openvsx = "openCAESAR.oml-luxor"

[openCAESAR-oml-luxor.passthru]
name = "oml-luxor"
publisher = "opencaesar"
marketplaceName = "oml-luxor"
marketplacePublisher = "openCAESAR"
license = "asl20"
downloadPage = "https://open-vsx.org/api/openCAESAR/oml-luxor/1.4.0/file/openCAESAR.oml-luxor-1.4.0.vsix"
homepage = ""

[usernamehw-commands]
src.openvsx = "usernamehw.commands"
fetch.openvsx = "usernamehw.commands"

[usernamehw-commands.passthru]
name = "commands"
publisher = "usernamehw"
marketplaceName = "commands"
marketplacePublisher = "usernamehw"
license = "mit"
changelog = "https://open-vsx.org/api/usernamehw/commands/1.6.0/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/usernamehw/commands/1.6.0/file/usernamehw.commands-1.6.0.vsix"
homepage = "https://github.com/usernamehw/vscode-commands#readme"

[marcinbar-vscode-squirrel]
src.openvsx = "marcinbar.vscode-squirrel"
fetch.openvsx = "marcinbar.vscode-squirrel"

[marcinbar-vscode-squirrel.passthru]
name = "vscode-squirrel"
publisher = "marcinbar"
marketplaceName = "vscode-squirrel"
marketplacePublisher = "marcinbar"
license = "mit"
downloadPage = "https://open-vsx.org/api/marcinbar/vscode-squirrel/0.0.24/file/marcinbar.vscode-squirrel-0.0.24.vsix"
homepage = "https://bitbucket.org/marcinbar91/vscode-squirrel#readme"

[gares-coq-elpi-lang]
src.openvsx = "gares.coq-elpi-lang"
fetch.openvsx = "gares.coq-elpi-lang"

[gares-coq-elpi-lang.passthru]
name = "coq-elpi-lang"
publisher = "gares"
marketplaceName = "coq-elpi-lang"
marketplacePublisher = "gares"
license = "mit"
changelog = "https://open-vsx.org/api/gares/coq-elpi-lang/0.0.5/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/gares/coq-elpi-lang/0.0.5/file/gares.coq-elpi-lang-0.0.5.vsix"
homepage = "https://github.com/LPCIC/coq-elpi-lang/README.md"

[augustocdias-tasks-shell-input]
src.openvsx = "augustocdias.tasks-shell-input"
fetch.openvsx = "augustocdias.tasks-shell-input"

[augustocdias-tasks-shell-input.passthru]
name = "tasks-shell-input"
publisher = "augustocdias"
marketplaceName = "tasks-shell-input"
marketplacePublisher = "augustocdias"
license = "mit"
changelog = "https://open-vsx.org/api/augustocdias/tasks-shell-input/1.7.5/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/augustocdias/tasks-shell-input/1.7.5/file/augustocdias.tasks-shell-input-1.7.5.vsix"
homepage = "https://github.com/augustocdias/vscode-shell-command#readme"

[johnbillion-vscode-wordpress-hooks]
src.openvsx = "johnbillion.vscode-wordpress-hooks"
fetch.openvsx = "johnbillion.vscode-wordpress-hooks"

[johnbillion-vscode-wordpress-hooks.passthru]
name = "vscode-wordpress-hooks"
publisher = "johnbillion"
marketplaceName = "vscode-wordpress-hooks"
marketplacePublisher = "johnbillion"
license = "gpl3Plus"
downloadPage = "https://open-vsx.org/api/johnbillion/vscode-wordpress-hooks/1.1.0/file/johnbillion.vscode-wordpress-hooks-1.1.0.vsix"
homepage = ""


[viper-admin-prusti-assistant]
src.openvsx = "viper-admin.prusti-assistant"
fetch.openvsx = "viper-admin.prusti-assistant"

[viper-admin-prusti-assistant.passthru]
name = "prusti-assistant"
publisher = "viper-admin"
marketplaceName = "prusti-assistant"
marketplacePublisher = "viper-admin"
license = "mit"
changelog = "https://open-vsx.org/api/viper-admin/prusti-assistant/0.11.2/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/viper-admin/prusti-assistant/0.11.2/file/viper-admin.prusti-assistant-0.11.2.vsix"
homepage = "https://github.com/viperproject/prusti-assistant"

[gera2ld-ipfs-editor-vscode]
src.openvsx = "gera2ld.ipfs-editor-vscode"
fetch.openvsx = "gera2ld.ipfs-editor-vscode"

[gera2ld-ipfs-editor-vscode.passthru]
name = "ipfs-editor-vscode"
publisher = "gera2ld"
marketplaceName = "ipfs-editor-vscode"
marketplacePublisher = "gera2ld"
license = "mit"
downloadPage = "https://open-vsx.org/api/gera2ld/ipfs-editor-vscode/0.1.5/file/gera2ld.ipfs-editor-vscode-0.1.5.vsix"
homepage = "https://github.com/gera2ld/ipfs-editor-vscode#readme"

[mamoru-vscode-fish-text]
src.openvsx = "mamoru.vscode-fish-text"
fetch.openvsx = "mamoru.vscode-fish-text"

[mamoru-vscode-fish-text.passthru]
name = "vscode-fish-text"
publisher = "mamoru"
marketplaceName = "vscode-fish-text"
marketplacePublisher = "mamoru"
license = "mit"
changelog = "https://open-vsx.org/api/mamoru/vscode-fish-text/1.2.0/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/mamoru/vscode-fish-text/1.2.0/file/mamoru.vscode-fish-text-1.2.0.vsix"
homepage = "https://github.com/AlexAtHome/vscode-fish-text#readme"

[Grafana-vscode-jsonnet]
src.openvsx = "Grafana.vscode-jsonnet"
fetch.openvsx = "Grafana.vscode-jsonnet"

[Grafana-vscode-jsonnet.passthru]
name = "vscode-jsonnet"
publisher = "grafana"
marketplaceName = "vscode-jsonnet"
marketplacePublisher = "Grafana"
license = "asl20"
downloadPage = "https://open-vsx.org/api/Grafana/vscode-jsonnet/0.3.3/file/Grafana.vscode-jsonnet-0.3.3.vsix"
homepage = ""

[weaveworks-vscode-gitops-tools]
src.openvsx = "weaveworks.vscode-gitops-tools"
fetch.openvsx = "weaveworks.vscode-gitops-tools"

[weaveworks-vscode-gitops-tools.passthru]
name = "vscode-gitops-tools"
publisher = "weaveworks"
marketplaceName = "vscode-gitops-tools"
marketplacePublisher = "weaveworks"
license = "mpl20"
changelog = "https://open-vsx.org/api/weaveworks/vscode-gitops-tools/0.22.5/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/weaveworks/vscode-gitops-tools/0.22.5/file/weaveworks.vscode-gitops-tools-0.22.5.vsix"
homepage = "https://github.com/weaveworks/vscode-gitops-tools"

[GaelicGrime-kenningsvsc]
src.openvsx = "GaelicGrime.kenningsvsc"
fetch.openvsx = "GaelicGrime.kenningsvsc"

[GaelicGrime-kenningsvsc.passthru]
name = "kenningsvsc"
publisher = "gaelicgrime"
marketplaceName = "kenningsvsc"
marketplacePublisher = "GaelicGrime"
license = "gpl3Only"
downloadPage = "https://open-vsx.org/api/GaelicGrime/kenningsvsc/linux-x64/0.1.18/file/GaelicGrime.kenningsvsc-0.1.18@linux-x64.vsix"
homepage = "https://github.com/GaelicGrime/kenningsVSC#readme"

[brunnerh-insert-unicode]
src.openvsx = "brunnerh.insert-unicode"
fetch.openvsx = "brunnerh.insert-unicode"

[brunnerh-insert-unicode.passthru]
name = "insert-unicode"
publisher = "brunnerh"
marketplaceName = "insert-unicode"
marketplacePublisher = "brunnerh"
license = "mit"
changelog = "https://open-vsx.org/api/brunnerh/insert-unicode/0.14.0/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/brunnerh/insert-unicode/0.14.0/file/brunnerh.insert-unicode-0.14.0.vsix"
homepage = "https://github.com/brunnerh/insert-unicode"

[malipetek-liquivelte]
src.openvsx = "malipetek.liquivelte"
fetch.openvsx = "malipetek.liquivelte"

[malipetek-liquivelte.passthru]
name = "liquivelte"
publisher = "malipetek"
marketplaceName = "liquivelte"
marketplacePublisher = "malipetek"
license = "mit"
changelog = "https://open-vsx.org/api/malipetek/liquivelte/1.3.5/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/malipetek/liquivelte/1.3.5/file/malipetek.liquivelte-1.3.5.vsix"
homepage = "https://github.com/malipetek/liquivelte-vscode#readme"

[h3knix-dateversion]
src.openvsx = "h3knix.dateversion"
fetch.openvsx = "h3knix.dateversion"

[h3knix-dateversion.passthru]
name = "dateversion"
publisher = "h3knix"
marketplaceName = "dateversion"
marketplacePublisher = "h3knix"
license = "mit"
changelog = "https://open-vsx.org/api/h3knix/dateversion/0.2.0/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/h3knix/dateversion/0.2.0/file/h3knix.dateversion-0.2.0.vsix"
homepage = "https://github.com/h3knix/vscode-dateversion/"

[PKief-material-product-icons]
src.openvsx = "PKief.material-product-icons"
fetch.openvsx = "PKief.material-product-icons"

[PKief-material-product-icons.passthru]
name = "material-product-icons"
publisher = "pkief"
marketplaceName = "material-product-icons"
marketplacePublisher = "PKief"
license = "mit"
changelog = "https://open-vsx.org/api/PKief/material-product-icons/1.4.1/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/PKief/material-product-icons/1.4.1/file/PKief.material-product-icons-1.4.1.vsix"
homepage = "https://github.com/PKief/vscode-material-product-icons/blob/master/README.md"

