jobs:
  nixCI:
    name: Nix CI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://cache.iog.io https://deemp.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=
            keep-outputs = true
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v1
        with:
          key: nix-${{ runner.os }}-update-${{ hashfiles('**/flake.nix', '**/flake.lock', 'haskell/**/*') }}
          linux-gc-enabled: true
          linux-max-store-size: 1000000000
          restore-keys: |
            nix-${{ runner.os }}-update-${{ hashfiles('**/flake.nix', '**/flake.lock', 'haskell/**/*') }}
            nix-${{ runner.os }}-update-
      - name: Config git for github-actions
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Format Nix files
        run: |-
          nix profile install nix-dev/#format
          nix run nix-dev/#format
      - name: Update flake locks
        run: |-
          nix profile install nix-dev/#updateLocks
          nix run nix-dev/#updateLocks
      - name: Check template VSCodium
        run: |
          nix profile install template/
          nix run template/ -- --list-extensions
      - env:
          CONFIG: .github/config.yaml
        name: Update extensions
        run: |-
          nix profile install nix-dev/#updateExtensions
          nix run nix-dev/#updateExtensions
      - name: Update extra extensions
        run: |-
          nix profile install nix-dev/#updateExtraExtensions
          nix run nix-dev/#updateExtraExtensions
      - name: Commit and push changes
        run: |-
          git add .
          git commit \
            -m "action: Update flake locks" \
            -m "action: Update extensions" \
            -m "action: Update extra extensions"
          git push
name: Nix CI
"on":
  pull_request: {}
  push: {}
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
